### ISSUE TITLE
Access 0.0.0.0:50500 get error 502

### ISSUE THREAD

**Issue by soandsoprogrammer** [jwarkentin/node-monkey#60]

**Comment by soandsoprogrammer** [comment]
let NodeMonkey = require("node-monkey")
let monkey = NodeMonkey({
  server: {
    host: '127.0.0.1',
    disableLocalOutput: true,
  },
})

setInterval(()=>{
    console.log(1222)
},5000)

Then, I get 404

**Comment by jwarkentin** [comment]
The problem is, you're explicitly binding to your localhost network interface by specifying `127.0.0.1` as the host in your server config and then trying to access the server with the any host address. If you want to use that as the host then you have to access `http://127.0.0.1:50500` or `http://localhost:50500` (on most machines) in your browser. If you bind to the default any host address with `0.0.0.0` in your server config then on most machines that binds to all local IPv4 network interfaces, meaning you can use any IP address that references your machine in the browser instead of just `localhost`.
